project:
  type: website
  output-dir: _output

website:
  title: "This Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
#    toc: true
    fontsize: 1.2em

